Bumping to 1.8.0
I have tested this change and it seems like bumping to Atom 1.8.0 is simple enough. APM's latest ver is 1.11.1 and is more complicated to update. When I updated it and tried to build Atom 1.8.0 against it I got the error: 

```bash
==> Removing existing $pkgdir/ directory...
==> Starting build()...
module.js:442
    throw err;
    ^

Error: Cannot find module 'node-gyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.resolve (internal/module.js:27:19)
    at new Install (/usr/lib/node_modules/atom-package-manager/lib/install.js:53:38)
    at Object.module.exports.run (/usr/lib/node_modules/atom-package-manager/lib/apm-cli.js:226:18)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/bin/apm:11:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
==> ERROR: A failure occurred in build().
    Aborting...
```